### ISSUE TITLE
La suppression d'une valeur de propriété n'est pas prise en compte dans l'interface

### ISSUE THREAD

**Issue by WebMSB** [webNeat/pwfs#27]
Après avoir supprimé ou modifié une valeur de propriété, la vue de l'instance est bien mise à jour. Par contre, après avoir changé d'instance courante et être revenu sur l'instance précédent, les modifications faites au préalable ne sont pas restituées. 

Il semblerait que la modif se fait bien en base car lorsqu'on change de curseur sur la classe, et qu'on revient sur notre classe courante, puis sur l'instance modifiée, on retrouve bien les modif faites.

dans le cas ou le data type property est multiple ça s'enregistre pas, dans la base de données je trouve new value here.

**Comment by webNeat** [comment]
réglée
