### ISSUE TITLE
Bouton suppression d’une valeur d’object property à déplacer à gauche

### ISSUE THREAD

**Issue by WebMSB** [webNeat/pwfs#3]

**Comment by webNeat** [comment]
Réglée : 009a8da61741cd8cf5ae2c1d9dfb01eb6ec87111

**Comment by WebMSB** [comment]
en fait, le bouton il est bien a gauche de la valeur.  mais vaut mieux ajouter un peu d'espace entre  le bouton et la valeur.

**Comment by webNeat** [comment]
C'est fait : 4c892a51b23f68ecfdfd8e858292833c55a344b2
Tu peux varier la valeur de "margin-right" pour varier la taille l'espace

**Comment by WebMSB** [comment]
d'accord. pour moi le ticket est résolu
