### ISSUE TITLE
Bouton suppression d’une instance à placer dans le contexte de la fenêtre d’Instances (pour sélectionner multiple instances et les supprimer)

### ISSUE THREAD

**Issue by WebMSB** [webNeat/pwfs#4]

**Comment by webNeat** [comment]
### Les deux fichiers à modifier
- WebContent/views/partials/browser.html ( entre les lignes 74 et 86 )
- WebContent/directives/browser.js

### Les étapes à faire
- Remplacer les buttons supprimer par des input du type checkbox
- Ajouter une variable dans le directive qui contient les ids des instances séléctionnées ( à toi de voir comment :P )
- Ajouter un button supprimer ( voir les lignes 63..68 )
- Ajouter une méthode qui se délanche lorsqu'on clique sur ce button et supprime toutes les instances séléctionner ( il suffit de boucler sur les instances séléctionnées et appéler la fonction `removeInstance` pour chacune )

**Comment by WebMSB** [comment]
est ce que le mieux ce n'est pas d'avoir une méthode de sélection multiple. genre on sélectionne qu'a travers  la souris.

**Comment by webNeat** [comment]
Tu veux dire comme la façon avec laquelle on séléctionne les icons dans le bureau ? non C'est compliqué !

**Comment by webNeat** [comment]
done
