### ISSUE TITLE
Affichage nom classe courante et instance courante (For project / For class / For individual)

### ISSUE THREAD

**Issue by WebMSB** [webNeat/pwfs#5]

**Comment by webNeat** [comment]
Je vais m'occuper de ça

**Comment by WebMSB** [comment]
ok cette issue est validée ! merci

**Comment by webNeat** [comment]
Done 9ea1de7675c0f4e45d5ef824c10ab6c8d24141e0 and 1313bbada7545c79b91c835e0ec1fe67d97f2744
