### ISSUE TITLE
Barre de navigation et footer

### ISSUE THREAD

**Issue by WebMSB** [webNeat/pwfs#6]
### Header
- lien vers le doc (en PDF) 
- bouton retour à la page d’accueil
### Footer
- bandeau SEAMLESS

**Comment by webNeat** [comment]
- Les liens du header peuvent être ajouter dans `WebContent/index.html:40`, voir ici pour un exemple: http://getbootstrap.com/components/#navbar-default

**Comment by WebMSB** [comment]
si tu n'a pas de remarque à propos de ce ticket. tu peux le fermer
